services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourPassword123!"
    ports:
      - "1433:1433"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=JobTracker;User Id=sa;Password=YourPassword123!;TrustServerCertificate=True;"
    depends_on:
      - sqlserver

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
